when:
  - event: push
    branch: main

steps:
  - name: testar-codigo
    image: oven/bun:alpine
    commands:
      - echo "Instalando dependências para os testes..."
      - bun install
      - echo "Executando a suíte de testes..."
      - bun test

  - name: deploy-elysia
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      BETTER_AUTH_SECRET:
        from_secret: better_auth_secret
    commands:
      - echo "Testes aprovados! Iniciando build da API..."
      - docker build -t api-bun:latest .

      - echo "Limpando versão anterior..."
      - docker rm -f api-bun || true

      - echo "Subindo o novo servidor Elysia com Better Auth..."
      - >
        docker run -d
        --name api-bun
        -p 3003:3000
        -v /opt/api-bun/data:/app/data
        -e DATABASE_URL=/app/data/sqlite.db
        -e DO_NOT_TRACK=1
        -e OTEL_SERVICE_NAME=api-bun
        -e OTEL_EXPORTER_URL=http://192.168.31.215:4318/v1/traces
        -e BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
        -e BETTER_AUTH_URL=http://api-bun.brunnoserver.duckdns.org
        --restart unless-stopped
        api-bun:latest

      - echo "Deploy concluído com sucesso!"
