skip_clone: true

steps:
  network-debug:
    image: alpine:3.22
    commands:
      - echo "===== resolv.conf ====="
      - cat /etc/resolv.conf

      - echo "===== interfaces ====="
      - ip addr

      - echo "===== routes ====="
      - ip route

      - echo "===== DNS ====="
      - nslookup gitea.brunnoserver.duckdns.org || true

      - echo "===== TCP RV2 ====="
      - nc -vz -w 5 192.168.31.1 443 || true

      - echo "===== GITEA HTTPS ====="
      - wget -S -O - -T 10 https://gitea.brunnoserver.duckdns.org/api/v1/version || true

      - echo "===== mantendo container ativo ====="
      - sleep 600