steps:
  - name: deploy-api-bun
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "Iniciando build da api-bun..."
      - docker build -t api-bun:latest .
      - docker stop api-bun || true
      - docker rm api-bun || true
      - docker run -d --name api-bun -p 3003:3000 --restart always api-bun:latest
      - echo "Deploy da api-bun concluído!"
    when:
      event: push #pipeline so ira ocorre quando um push na main acontecer
      branch: main